language: php 

compiler:
  - g++
  - clang++

os:
  - linux
#  - osx

php:
  - 7.0
  - 7.1

notifications:
  email: team@swoole.com

before_script:
    - cmake . && make -j install

script:
    - exit 0


