language: php 

compiler:
  - gcc
  - clang

os:
  - linux
#  - osx

php:
  - 7.0
  - 7.1

notifications:
  email: team@swoole.com

before_script:
    - phpize && ./configure && make clean && make

script:
    - exit 0


